#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef APPGROUPSDK_SWIFT_H
#define APPGROUPSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AppGroupSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS_NAMED("AppDeviceInfo")
@interface SFMCAppDeviceInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull baseUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull applicationId;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceId;
@property (nonatomic, copy) NSString * _Nonnull accessToken;
@property (nonatomic, readonly, copy) NSString * _Nonnull mcsdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable subscriberToken;
@property (nonatomic, readonly, copy) NSString * _Nullable tenantId;
@property (nonatomic, readonly, copy) NSString * _Nullable sessionId;
@property (nonatomic, readonly, copy) NSString * _Nullable userId;
@property (nonatomic, readonly, copy) NSString * _Nullable appVersion;
/// Initializes AppDeviceInfo with device and app configuration.
/// All parameters are required to fully represent device state shared between app and extensions.
- (nonnull instancetype)initWithBaseUrl:(NSString * _Nonnull)baseUrl applicationId:(NSString * _Nonnull)applicationId deviceId:(NSString * _Nonnull)deviceId accessToken:(NSString * _Nonnull)accessToken mcsdkVersion:(NSString * _Nonnull)mcsdkVersion subscriberToken:(NSString * _Nullable)subscriberToken tenantId:(NSString * _Nullable)tenantId sessionId:(NSString * _Nullable)sessionId userId:(NSString * _Nullable)userId appVersion:(NSString * _Nullable)appVersion OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum SFMCDataStoreStatus : NSInteger;
SWIFT_CLASS_NAMED("AppDeviceInfoFetchResult")
@interface SFMCAppDeviceInfoFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCAppDeviceInfo * _Nullable value;
- (nonnull instancetype)initWithStatus:(enum SFMCDataStoreStatus)status value:(SFMCAppDeviceInfo * _Nullable)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("AppDeviceInfoStore")
@interface SFMCAppDeviceInfoStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCAppDeviceInfoStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCAppDeviceInfoFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCAppDeviceInfo * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

enum SFExtensionModuleName : NSInteger;
@interface SFMCAppDeviceInfoStore (SWIFT_EXTENSION(AppGroupSDK))
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId;
- (SFMCAppDeviceInfoFetchResult * _Nonnull)fetchModuleScopedModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleScopedModelData:(SFMCAppDeviceInfo * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_PROTOCOL_NAMED("AppIdProviding")
@protocol SFMCAppIdProviding
- (enum SFMCDataStoreStatus)storeAppId:(NSString * _Nonnull)appId forModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)appIdForModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("AppIdProvider")
@interface SFMCAppIdProvider : NSObject <SFMCAppIdProviding>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)appIdForModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)storeAppId:(NSString * _Nonnull)appId forModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SFMCCarouselActionType, "CarouselActionType", open) {
  SFMCCarouselActionTypeOpenApp = 0,
  SFMCCarouselActionTypeOpenDeepLink = 1,
  SFMCCarouselActionTypeOpenWebUrl = 2,
  SFMCCarouselActionTypeOpenCloudPage = 3,
};

SWIFT_CLASS_NAMED("CarouselClickModel")
@interface SFMCCarouselClickModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull notificationUniqueId;
@property (nonatomic, readonly) BOOL isCarouselClick;
@property (nonatomic, readonly) NSInteger clickIndex;
@property (nonatomic, readonly) enum SFMCCarouselActionType actionType;
@property (nonatomic, readonly, copy) NSString * _Nullable actionUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull panelId;
- (nonnull instancetype)initWithNotificationUniqueId:(NSString * _Nonnull)notificationUniqueId isCarouselClick:(BOOL)isCarouselClick clickIndex:(NSInteger)clickIndex actionType:(enum SFMCCarouselActionType)actionType actionUrl:(NSString * _Nullable)actionUrl panelId:(NSString * _Nonnull)panelId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("CarouselClickModelFetchResult")
@interface SFMCCarouselClickModelFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCCarouselClickModel * _Nullable value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("CarouselClickModelStore")
@interface SFMCCarouselClickModelStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCCarouselClickModelStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCCarouselClickModelFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCCarouselClickModel * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

@interface SFMCCarouselClickModelStore (SWIFT_EXTENSION(AppGroupSDK))
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId;
- (SFMCCarouselClickModelFetchResult * _Nonnull)fetchModuleScopedModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleScopedModelData:(SFMCCarouselClickModel * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

enum SFMCRichFeatureActionType : NSInteger;
SWIFT_CLASS_NAMED("CarouselRichFeatureMetaData")
@interface SFMCCarouselRichFeatureMeta : NSObject
@property (nonatomic) enum SFMCCarouselActionType actionType;
@property (nonatomic) enum SFMCRichFeatureActionType richFeatureActionType;
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)initWithActionType:(enum SFMCCarouselActionType)actionType richFeatureActionType:(enum SFMCRichFeatureActionType)richFeatureActionType url:(NSString * _Nullable)url OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// :nodoc:
SWIFT_PROTOCOL_NAMED("RichFeatureMetaProviding")
@protocol SFMCRichFeatureMetaProviding
- (SFMCCarouselRichFeatureMeta * _Nullable)getRichFeaturesMetaDataFromInfo:(NSDictionary * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (SFMCCarouselClickModel * _Nullable)getCarouselClickModel SWIFT_WARN_UNUSED_RESULT;
@end

/// :nodoc:
/// RichFeatureMetaProvider returns CarouselRichFeatureMetaData when user click on any notification
SWIFT_CLASS_NAMED("CarouselRichFeatureMetaProvider")
@interface SFMCCarouselRichFeatureMetaProvider : NSObject <SFMCRichFeatureMetaProviding>
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId OBJC_DESIGNATED_INITIALIZER;
- (SFMCCarouselRichFeatureMeta * _Nullable)getRichFeaturesMetaDataFromInfo:(NSDictionary * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (SFMCCarouselClickModel * _Nullable)getCarouselClickModel SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SFMCDataStoreStatus, "DataStoreStatus", open) {
  SFMCDataStoreStatusSuccess = 0,
  SFMCDataStoreStatusDirectoryUrlNotFound = 1,
  SFMCDataStoreStatusNotFileUrl = 2,
  SFMCDataStoreStatusJsonEncodingError = 3,
  SFMCDataStoreStatusFileSaveError = 4,
  SFMCDataStoreStatusFileReadError = 5,
  SFMCDataStoreStatusJsonDecodingError = 6,
  SFMCDataStoreStatusDataStoreUnavailable = 7,
};

enum FeatureFlagStatus : NSInteger;
SWIFT_CLASS_NAMED("DeliveryReceiptConfig")
@interface SFMCDeliveryReceiptConfig : NSObject
@property (nonatomic, readonly) enum FeatureFlagStatus featureFlag;
- (nonnull instancetype)initWithFeatureFlag:(NSInteger)featureFlag OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum PNStatus : NSInteger;
SWIFT_CLASS_NAMED("DeliveryReceiptPNModel")
@interface SFMCDeliveryReceiptPNModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageId;
@property (nonatomic, readonly, copy) NSString * _Nullable requestId;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageType;
@property (nonatomic, readonly) NSTimeInterval eventDateUtc;
@property (nonatomic, copy) NSString * _Nullable propertyBag;
@property (nonatomic) enum PNStatus status;
@property (nonatomic, copy) NSString * _Nullable userId;
- (nonnull instancetype)initWithUuid:(NSString * _Nonnull)uuid messageId:(NSString * _Nonnull)messageId requestId:(NSString * _Nullable)requestId messageType:(NSString * _Nonnull)messageType eventDateUtc:(NSTimeInterval)eventDateUtc propertyBag:(NSString * _Nullable)propertyBag status:(enum PNStatus)status userId:(NSString * _Nullable)userId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface SFMCDeliveryReceiptPNModel (SWIFT_EXTENSION(AppGroupSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

SWIFT_CLASS_NAMED("DeliveryReceiptsModel")
@interface SFMCDeliveryReceiptsModel : NSObject
@property (nonatomic, copy) NSArray<SFMCDeliveryReceiptPNModel *> * _Nonnull pnData;
- (nonnull instancetype)initWithPnData:(NSArray<SFMCDeliveryReceiptPNModel *> * _Nonnull)pnData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("DeliveryReceiptsModelFetchResult")
@interface SFMCDeliveryReceiptsModelFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCDeliveryReceiptsModel * _Nullable value;
- (nonnull instancetype)initWithStatus:(enum SFMCDataStoreStatus)status value:(SFMCDeliveryReceiptsModel * _Nullable)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("DeliveryReceiptsModelStore")
@interface SFMCDeliveryReceiptsModelStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCDeliveryReceiptsModelStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCDeliveryReceiptsModelFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCDeliveryReceiptsModel * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

@interface SFMCDeliveryReceiptsModelStore (SWIFT_EXTENSION(AppGroupSDK))
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId;
- (SFMCDeliveryReceiptsModelFetchResult * _Nonnull)fetchModuleScopedModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleScopedModelData:(SFMCDeliveryReceiptsModel * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SFExtensionModuleName, "ExtensionModuleName", open) {
  SFExtensionModuleNameMarketingEngagement = 1,
  SFExtensionModuleNameMobileAppMessaging = 2,
};

SWIFT_CLASS_NAMED("FeatureConfigDetail")
@interface SFMCFeatureConfigDetail : NSObject
@property (nonatomic, readonly, strong) SFMCDeliveryReceiptConfig * _Nonnull deliveryReceiptConfig;
- (nonnull instancetype)initWithDeliveryReceiptConfig:(SFMCDeliveryReceiptConfig * _Nonnull)deliveryReceiptConfig OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FeatureConfigDetailFetchResult")
@interface SFMCFeatureConfigDetailFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCFeatureConfigDetail * _Nullable value;
- (nonnull instancetype)initWithStatus:(enum SFMCDataStoreStatus)status value:(SFMCFeatureConfigDetail * _Nullable)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FeatureConfigDetailStore")
@interface SFMCFeatureConfigDetailStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCFeatureConfigDetailStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCFeatureConfigDetailFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCFeatureConfigDetail * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

@interface SFMCFeatureConfigDetailStore (SWIFT_EXTENSION(AppGroupSDK))
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId;
- (SFMCFeatureConfigDetailFetchResult * _Nonnull)fetchModuleScopedModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleScopedModelData:(SFMCFeatureConfigDetail * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, FeatureFlagStatus, open) {
  FeatureFlagStatusDisabled = 0,
  FeatureFlagStatusEnabled = 1,
};

SWIFT_CLASS_NAMED("ModuleAppMapping")
@interface SFMCModuleAppMapping : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull moduleName;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
- (nonnull instancetype)initWithModuleName:(enum SFExtensionModuleName)moduleName appId:(NSString * _Nonnull)appId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SFMCModuleAppMappings;
SWIFT_CLASS_NAMED("ModuleAppMappingFetchResult")
@interface SFMCModuleAppMappingFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCModuleAppMappings * _Nullable value;
- (nonnull instancetype)initWithStatus:(enum SFMCDataStoreStatus)status value:(SFMCModuleAppMappings * _Nullable)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("ModuleAppMappingStore")
@interface SFMCModuleAppMappingStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCModuleAppMappingStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCModuleAppMappingFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCModuleAppMappings * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleAppMapping:(SFMCModuleAppMapping * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("ModuleAppMappings")
@interface SFMCModuleAppMappings : NSObject
@property (nonatomic, readonly, copy) NSArray<SFMCModuleAppMapping *> * _Nonnull mappings;
- (nonnull instancetype)initWithMappings:(NSArray<SFMCModuleAppMapping *> * _Nonnull)mappings OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)fetchAppIdForModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// :nodoc:
/// Destination enum that defines the destination types in the <code>_co</code> field
typedef SWIFT_ENUM(NSInteger, PNContextDestination, open) {
/// No destination specified
  PNContextDestinationNone = 0,
/// Marketing Cloud Engagement
  PNContextDestinationMce = 1,
/// Mobile App Messaging
  PNContextDestinationMam = 2,
/// Data Cloud
  PNContextDestinationDataCloud = 4,
};

enum PNContextSource : NSInteger;
@class NSNumber;
/// :nodoc:
/// Context information from push notification
SWIFT_CLASS("_TtC11AppGroupSDK13PNContextInfo")
@interface PNContextInfo : NSObject
@property (nonatomic, readonly) enum PNContextSource source;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull destinationsArray;
@property (nonatomic, readonly, copy) NSString * _Nullable businessUnitId;
- (nonnull instancetype)initWithSource:(enum PNContextSource)source destinationsArray:(NSArray<NSNumber *> * _Nonnull)destinationsArray businessUnitId:(NSString * _Nullable)businessUnitId OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isInavlidOrAbsentContext SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// :nodoc:
/// Source enum that defines the source types in the <code>_co</code> field
typedef SWIFT_ENUM(NSInteger, PNContextSource, open) {
/// No source specified
  PNContextSourceNone = 0,
/// Marketing Cloud Engagement
  PNContextSourceMce = 1,
/// Mobile App Messaging
  PNContextSourceMam = 2,
};

@class UNNotificationContent;
/// :nodoc:
/// Utility class for handling push notification context operations
SWIFT_CLASS("_TtC11AppGroupSDK14PNContextUtils")
@interface PNContextUtils : NSObject
/// Private initializer to prevent instantiation
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Extracts the <code>_co</code> field from iOS push notification content
/// \param content The UNNotificationContent from the push notification
///
///
/// returns:
/// The _co field value as an optional string
+ (NSString * _Nullable)extractContextFieldFromContent:(UNNotificationContent * _Nonnull)content SWIFT_WARN_UNUSED_RESULT;
/// Parses the _co field string and returns a PNContextInfo object
/// \param contextString The _co field value as a string (base64 encoded)
///
///
/// returns:
/// A PNContextInfo object parsed from the string
+ (PNContextInfo * _Nonnull)parseContextInfoFromContextString:(NSString * _Nonnull)contextString SWIFT_WARN_UNUSED_RESULT;
/// Extracts the <code>_co</code> field from iOS push notification content and parses it
/// \param content The UNNotificationContent from the push notification
///
///
/// returns:
/// A PNContextInfo object
+ (PNContextInfo * _Nonnull)parseContextInfoFromContent:(UNNotificationContent * _Nonnull)content SWIFT_WARN_UNUSED_RESULT;
/// Extracts the <code>_co</code> field from iOS push notification content’s user info and parses it
/// \param userInfo The userInfo from the push notification
///
///
/// returns:
/// A PNContextInfo object
+ (PNContextInfo * _Nonnull)parseContextInfoFromUserInfo:(NSDictionary * _Nonnull)userInfo SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, PNStatus, open) {
  PNStatusPending = 0,
  PNStatusFailed = 1,
};

typedef SWIFT_ENUM_NAMED(NSInteger, SFMCRichFeatureActionType, "RichFeatureActionType", open) {
  SFMCRichFeatureActionTypeNone = 0,
  SFMCRichFeatureActionTypeCarouselBodyClick = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef APPGROUPSDK_SWIFT_H
#define APPGROUPSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AppGroupSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS_NAMED("AppDeviceInfo")
@interface SFMCAppDeviceInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull baseUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull applicationId;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceId;
@property (nonatomic, copy) NSString * _Nonnull accessToken;
@property (nonatomic, readonly, copy) NSString * _Nonnull mcsdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable subscriberToken;
@property (nonatomic, readonly, copy) NSString * _Nullable tenantId;
@property (nonatomic, readonly, copy) NSString * _Nullable sessionId;
@property (nonatomic, readonly, copy) NSString * _Nullable userId;
@property (nonatomic, readonly, copy) NSString * _Nullable appVersion;
/// Initializes AppDeviceInfo with device and app configuration.
/// All parameters are required to fully represent device state shared between app and extensions.
- (nonnull instancetype)initWithBaseUrl:(NSString * _Nonnull)baseUrl applicationId:(NSString * _Nonnull)applicationId deviceId:(NSString * _Nonnull)deviceId accessToken:(NSString * _Nonnull)accessToken mcsdkVersion:(NSString * _Nonnull)mcsdkVersion subscriberToken:(NSString * _Nullable)subscriberToken tenantId:(NSString * _Nullable)tenantId sessionId:(NSString * _Nullable)sessionId userId:(NSString * _Nullable)userId appVersion:(NSString * _Nullable)appVersion OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum SFMCDataStoreStatus : NSInteger;
SWIFT_CLASS_NAMED("AppDeviceInfoFetchResult")
@interface SFMCAppDeviceInfoFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCAppDeviceInfo * _Nullable value;
- (nonnull instancetype)initWithStatus:(enum SFMCDataStoreStatus)status value:(SFMCAppDeviceInfo * _Nullable)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("AppDeviceInfoStore")
@interface SFMCAppDeviceInfoStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCAppDeviceInfoStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCAppDeviceInfoFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCAppDeviceInfo * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

enum SFExtensionModuleName : NSInteger;
@interface SFMCAppDeviceInfoStore (SWIFT_EXTENSION(AppGroupSDK))
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId;
- (SFMCAppDeviceInfoFetchResult * _Nonnull)fetchModuleScopedModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleScopedModelData:(SFMCAppDeviceInfo * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_PROTOCOL_NAMED("AppIdProviding")
@protocol SFMCAppIdProviding
- (enum SFMCDataStoreStatus)storeAppId:(NSString * _Nonnull)appId forModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)appIdForModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("AppIdProvider")
@interface SFMCAppIdProvider : NSObject <SFMCAppIdProviding>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)appIdForModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)storeAppId:(NSString * _Nonnull)appId forModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SFMCCarouselActionType, "CarouselActionType", open) {
  SFMCCarouselActionTypeOpenApp = 0,
  SFMCCarouselActionTypeOpenDeepLink = 1,
  SFMCCarouselActionTypeOpenWebUrl = 2,
  SFMCCarouselActionTypeOpenCloudPage = 3,
};

SWIFT_CLASS_NAMED("CarouselClickModel")
@interface SFMCCarouselClickModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull notificationUniqueId;
@property (nonatomic, readonly) BOOL isCarouselClick;
@property (nonatomic, readonly) NSInteger clickIndex;
@property (nonatomic, readonly) enum SFMCCarouselActionType actionType;
@property (nonatomic, readonly, copy) NSString * _Nullable actionUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull panelId;
- (nonnull instancetype)initWithNotificationUniqueId:(NSString * _Nonnull)notificationUniqueId isCarouselClick:(BOOL)isCarouselClick clickIndex:(NSInteger)clickIndex actionType:(enum SFMCCarouselActionType)actionType actionUrl:(NSString * _Nullable)actionUrl panelId:(NSString * _Nonnull)panelId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("CarouselClickModelFetchResult")
@interface SFMCCarouselClickModelFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCCarouselClickModel * _Nullable value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("CarouselClickModelStore")
@interface SFMCCarouselClickModelStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCCarouselClickModelStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCCarouselClickModelFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCCarouselClickModel * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

@interface SFMCCarouselClickModelStore (SWIFT_EXTENSION(AppGroupSDK))
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId;
- (SFMCCarouselClickModelFetchResult * _Nonnull)fetchModuleScopedModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleScopedModelData:(SFMCCarouselClickModel * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

enum SFMCRichFeatureActionType : NSInteger;
SWIFT_CLASS_NAMED("CarouselRichFeatureMetaData")
@interface SFMCCarouselRichFeatureMeta : NSObject
@property (nonatomic) enum SFMCCarouselActionType actionType;
@property (nonatomic) enum SFMCRichFeatureActionType richFeatureActionType;
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)initWithActionType:(enum SFMCCarouselActionType)actionType richFeatureActionType:(enum SFMCRichFeatureActionType)richFeatureActionType url:(NSString * _Nullable)url OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// :nodoc:
SWIFT_PROTOCOL_NAMED("RichFeatureMetaProviding")
@protocol SFMCRichFeatureMetaProviding
- (SFMCCarouselRichFeatureMeta * _Nullable)getRichFeaturesMetaDataFromInfo:(NSDictionary * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (SFMCCarouselClickModel * _Nullable)getCarouselClickModel SWIFT_WARN_UNUSED_RESULT;
@end

/// :nodoc:
/// RichFeatureMetaProvider returns CarouselRichFeatureMetaData when user click on any notification
SWIFT_CLASS_NAMED("CarouselRichFeatureMetaProvider")
@interface SFMCCarouselRichFeatureMetaProvider : NSObject <SFMCRichFeatureMetaProviding>
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId OBJC_DESIGNATED_INITIALIZER;
- (SFMCCarouselRichFeatureMeta * _Nullable)getRichFeaturesMetaDataFromInfo:(NSDictionary * _Nonnull)info SWIFT_WARN_UNUSED_RESULT;
- (SFMCCarouselClickModel * _Nullable)getCarouselClickModel SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SFMCDataStoreStatus, "DataStoreStatus", open) {
  SFMCDataStoreStatusSuccess = 0,
  SFMCDataStoreStatusDirectoryUrlNotFound = 1,
  SFMCDataStoreStatusNotFileUrl = 2,
  SFMCDataStoreStatusJsonEncodingError = 3,
  SFMCDataStoreStatusFileSaveError = 4,
  SFMCDataStoreStatusFileReadError = 5,
  SFMCDataStoreStatusJsonDecodingError = 6,
  SFMCDataStoreStatusDataStoreUnavailable = 7,
};

enum FeatureFlagStatus : NSInteger;
SWIFT_CLASS_NAMED("DeliveryReceiptConfig")
@interface SFMCDeliveryReceiptConfig : NSObject
@property (nonatomic, readonly) enum FeatureFlagStatus featureFlag;
- (nonnull instancetype)initWithFeatureFlag:(NSInteger)featureFlag OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum PNStatus : NSInteger;
SWIFT_CLASS_NAMED("DeliveryReceiptPNModel")
@interface SFMCDeliveryReceiptPNModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageId;
@property (nonatomic, readonly, copy) NSString * _Nullable requestId;
@property (nonatomic, readonly, copy) NSString * _Nonnull messageType;
@property (nonatomic, readonly) NSTimeInterval eventDateUtc;
@property (nonatomic, copy) NSString * _Nullable propertyBag;
@property (nonatomic) enum PNStatus status;
@property (nonatomic, copy) NSString * _Nullable userId;
- (nonnull instancetype)initWithUuid:(NSString * _Nonnull)uuid messageId:(NSString * _Nonnull)messageId requestId:(NSString * _Nullable)requestId messageType:(NSString * _Nonnull)messageType eventDateUtc:(NSTimeInterval)eventDateUtc propertyBag:(NSString * _Nullable)propertyBag status:(enum PNStatus)status userId:(NSString * _Nullable)userId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface SFMCDeliveryReceiptPNModel (SWIFT_EXTENSION(AppGroupSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

SWIFT_CLASS_NAMED("DeliveryReceiptsModel")
@interface SFMCDeliveryReceiptsModel : NSObject
@property (nonatomic, copy) NSArray<SFMCDeliveryReceiptPNModel *> * _Nonnull pnData;
- (nonnull instancetype)initWithPnData:(NSArray<SFMCDeliveryReceiptPNModel *> * _Nonnull)pnData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("DeliveryReceiptsModelFetchResult")
@interface SFMCDeliveryReceiptsModelFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCDeliveryReceiptsModel * _Nullable value;
- (nonnull instancetype)initWithStatus:(enum SFMCDataStoreStatus)status value:(SFMCDeliveryReceiptsModel * _Nullable)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("DeliveryReceiptsModelStore")
@interface SFMCDeliveryReceiptsModelStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCDeliveryReceiptsModelStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCDeliveryReceiptsModelFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCDeliveryReceiptsModel * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

@interface SFMCDeliveryReceiptsModelStore (SWIFT_EXTENSION(AppGroupSDK))
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId;
- (SFMCDeliveryReceiptsModelFetchResult * _Nonnull)fetchModuleScopedModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleScopedModelData:(SFMCDeliveryReceiptsModel * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SFExtensionModuleName, "ExtensionModuleName", open) {
  SFExtensionModuleNameMarketingEngagement = 1,
  SFExtensionModuleNameMobileAppMessaging = 2,
};

SWIFT_CLASS_NAMED("FeatureConfigDetail")
@interface SFMCFeatureConfigDetail : NSObject
@property (nonatomic, readonly, strong) SFMCDeliveryReceiptConfig * _Nonnull deliveryReceiptConfig;
- (nonnull instancetype)initWithDeliveryReceiptConfig:(SFMCDeliveryReceiptConfig * _Nonnull)deliveryReceiptConfig OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FeatureConfigDetailFetchResult")
@interface SFMCFeatureConfigDetailFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCFeatureConfigDetail * _Nullable value;
- (nonnull instancetype)initWithStatus:(enum SFMCDataStoreStatus)status value:(SFMCFeatureConfigDetail * _Nullable)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FeatureConfigDetailStore")
@interface SFMCFeatureConfigDetailStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCFeatureConfigDetailStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCFeatureConfigDetailFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCFeatureConfigDetail * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

@interface SFMCFeatureConfigDetailStore (SWIFT_EXTENSION(AppGroupSDK))
- (nonnull instancetype)initWithModule:(enum SFExtensionModuleName)module_ appId:(NSString * _Nonnull)appId;
- (SFMCFeatureConfigDetailFetchResult * _Nonnull)fetchModuleScopedModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleScopedModelData:(SFMCFeatureConfigDetail * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, FeatureFlagStatus, open) {
  FeatureFlagStatusDisabled = 0,
  FeatureFlagStatusEnabled = 1,
};

SWIFT_CLASS_NAMED("ModuleAppMapping")
@interface SFMCModuleAppMapping : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull moduleName;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
- (nonnull instancetype)initWithModuleName:(enum SFExtensionModuleName)moduleName appId:(NSString * _Nonnull)appId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SFMCModuleAppMappings;
SWIFT_CLASS_NAMED("ModuleAppMappingFetchResult")
@interface SFMCModuleAppMappingFetchResult : NSObject
@property (nonatomic, readonly) enum SFMCDataStoreStatus status;
@property (nonatomic, readonly, strong) SFMCModuleAppMappings * _Nullable value;
- (nonnull instancetype)initWithStatus:(enum SFMCDataStoreStatus)status value:(SFMCModuleAppMappings * _Nullable)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("ModuleAppMappingStore")
@interface SFMCModuleAppMappingStore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface SFMCModuleAppMappingStore (SWIFT_EXTENSION(AppGroupSDK))
- (SFMCModuleAppMappingFetchResult * _Nonnull)fetchModelData SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModelData:(SFMCModuleAppMappings * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
- (enum SFMCDataStoreStatus)saveModuleAppMapping:(SFMCModuleAppMapping * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("ModuleAppMappings")
@interface SFMCModuleAppMappings : NSObject
@property (nonatomic, readonly, copy) NSArray<SFMCModuleAppMapping *> * _Nonnull mappings;
- (nonnull instancetype)initWithMappings:(NSArray<SFMCModuleAppMapping *> * _Nonnull)mappings OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)fetchAppIdForModule:(enum SFExtensionModuleName)module_ SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// :nodoc:
/// Destination enum that defines the destination types in the <code>_co</code> field
typedef SWIFT_ENUM(NSInteger, PNContextDestination, open) {
/// No destination specified
  PNContextDestinationNone = 0,
/// Marketing Cloud Engagement
  PNContextDestinationMce = 1,
/// Mobile App Messaging
  PNContextDestinationMam = 2,
/// Data Cloud
  PNContextDestinationDataCloud = 4,
};

enum PNContextSource : NSInteger;
@class NSNumber;
/// :nodoc:
/// Context information from push notification
SWIFT_CLASS("_TtC11AppGroupSDK13PNContextInfo")
@interface PNContextInfo : NSObject
@property (nonatomic, readonly) enum PNContextSource source;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull destinationsArray;
@property (nonatomic, readonly, copy) NSString * _Nullable businessUnitId;
- (nonnull instancetype)initWithSource:(enum PNContextSource)source destinationsArray:(NSArray<NSNumber *> * _Nonnull)destinationsArray businessUnitId:(NSString * _Nullable)businessUnitId OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isInavlidOrAbsentContext SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// :nodoc:
/// Source enum that defines the source types in the <code>_co</code> field
typedef SWIFT_ENUM(NSInteger, PNContextSource, open) {
/// No source specified
  PNContextSourceNone = 0,
/// Marketing Cloud Engagement
  PNContextSourceMce = 1,
/// Mobile App Messaging
  PNContextSourceMam = 2,
};

@class UNNotificationContent;
/// :nodoc:
/// Utility class for handling push notification context operations
SWIFT_CLASS("_TtC11AppGroupSDK14PNContextUtils")
@interface PNContextUtils : NSObject
/// Private initializer to prevent instantiation
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Extracts the <code>_co</code> field from iOS push notification content
/// \param content The UNNotificationContent from the push notification
///
///
/// returns:
/// The _co field value as an optional string
+ (NSString * _Nullable)extractContextFieldFromContent:(UNNotificationContent * _Nonnull)content SWIFT_WARN_UNUSED_RESULT;
/// Parses the _co field string and returns a PNContextInfo object
/// \param contextString The _co field value as a string (base64 encoded)
///
///
/// returns:
/// A PNContextInfo object parsed from the string
+ (PNContextInfo * _Nonnull)parseContextInfoFromContextString:(NSString * _Nonnull)contextString SWIFT_WARN_UNUSED_RESULT;
/// Extracts the <code>_co</code> field from iOS push notification content and parses it
/// \param content The UNNotificationContent from the push notification
///
///
/// returns:
/// A PNContextInfo object
+ (PNContextInfo * _Nonnull)parseContextInfoFromContent:(UNNotificationContent * _Nonnull)content SWIFT_WARN_UNUSED_RESULT;
/// Extracts the <code>_co</code> field from iOS push notification content’s user info and parses it
/// \param userInfo The userInfo from the push notification
///
///
/// returns:
/// A PNContextInfo object
+ (PNContextInfo * _Nonnull)parseContextInfoFromUserInfo:(NSDictionary * _Nonnull)userInfo SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, PNStatus, open) {
  PNStatusPending = 0,
  PNStatusFailed = 1,
};

typedef SWIFT_ENUM_NAMED(NSInteger, SFMCRichFeatureActionType, "RichFeatureActionType", open) {
  SFMCRichFeatureActionTypeNone = 0,
  SFMCRichFeatureActionTypeCarouselBodyClick = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
